### PR TITLE
First draft of multi-problem docs

### PR DESCRIPTION
**Pull request by cwbeitel**
vis. issue https://github.com/tensorflow/tensor2tensor/issues/1394

### CODE REVIEW

**Comment by afrozenator** [comment]
Thanks a LOT for this @cwbeitel  -  Should we merge it in?

**Comment by cwbeitel** [comment]
@afrozenator Ah I left the [WIP] on there because I hadn't run any of the commands there yet, finding little changes in doing so. Just started datagen running this afternoon so it might be a day before I've test run training as well. I'll push those changes and if you think it would be helpful to people right away feel free to merge it and I'll send a follow-on, otherwise we can let it sit a day.

**Comment by afrozenator** [comment]
Makes sense to wait I think -- thanks again @cwbeitel  -- do ping me when you feel it is ready, thanks!

**Comment by cwbeitel** [comment]
@afrozenator gtg!

**Comment by afrozenator** [comment]
Many many thanks @cwbeitel !

**Pull request merged**
