### PR TITLE
Use ByteTextEncoding() for encoding strings in character based models

### PR DESCRIPTION
**Pull request by vthorsteinsson**
This PR modifies `wmt.py` to use `text_encoder.ByteTextEncoder()` to **encode** source and target strings in its character based data generators. This synchronizes the behavior with `problem_hparams.py` which uses `text_encoder.ByteTextEncoder()` to **decode** inferred strings. Prior to this PR, encodes and decodes in character models are different and results therefore incorrect.

The PR also defines the constant `EOS` with the value 1 to avoid a "magic constant" appearing in the source code.

### CODE REVIEW

**Comment by vthorsteinsson** [comment]
No changes are needed in t2t-datagen since it never calls `character_generator()` directly. Instead, it calls the higher-level functions such as `wmt.parsing_character_generator()` and `wmt.ende_character_generator()`, but the signatures of those haven't changed (and don't need to change).

I will look at eliminating the no-vocab option and update the PR. This will require a change to `wmt_test.py` as well.

**Comment by vthorsteinsson** [comment]
This should be OK now @lukaszkaiser

**Comment by lukaszkaiser** [comment]
Great thanks Villi!

**Comment by vthorsteinsson** [comment]
My pleasure!

**Pull request merged**
