### PR TITLE
Handling the cases where the target_modality is a dict

### PR DESCRIPTION
**Pull request by MostafaDehghani**
Handling the cases where the target_modality is a dict (mostly in functions used at inference time) in t2t_model and transformer.

### CODE REVIEW

**Comment by afrozenator** [comment]
@MostafaDehghani - Same problem as earlier, can you see it the git commit emails are the same as the CLA email (or maybe sign the CLA again with the git commit log email)?

Here is what I see when I see the commits, note that the avatars are different, implying different email addresses?

image

Thanks

**Comment by MostafaDehghani** [comment]
Thanks @afrozenator. This is so weird! I added another email address that I have to the CLA agreement (although I'm pretty sure I didn't use it when I sent the pull request). Hope this solves the problem. I think I also need to sync my PR...

**Comment by afrozenator** [comment]
@googlebot rescan

**Comment by afrozenator** [comment]
@MostafaDehghani -- let's see if that does the trick

c.f. https://opensource.google.com/docs/cla/

**Comment by afrozenator** [comment]
@googlebot rescan

**Comment by MostafaDehghani** [comment]
@afrozenator I think I got what is the problem :) I'm going to close this PR and submit a fresh one soon :)

**Pull request closed without merging**
