### PR TITLE
CNN/Dailymail Summarization

### PR DESCRIPTION
**Pull request by urvashik**
Adding the CNN/Dailymail summarization problem: Summarize news articles to their respective story highlights.

### CODE REVIEW

**Comment by pltrdy** [comment]
Interesting PR, but I get error when running generation:

## Command
after installing from your branch:
```
git remote add urvashik https://github.com/urvashik/tensor2tensor.git
git pull urvashik master
pip2 install . --upgrade
```
I run generation:
```
t2t-trainer \
  --generate_data \
  --data_dir="$data" \
  --problems=summarize_cnn_dailymail32k \
  --model=transformer \
  --hparams_set=transformer_base_single_gpu \
  --output_dir="$root"

```
## Output
```
INFO:tensorflow:Generating data for summarize_cnn_dailymail32k
INFO:tensorflow:Found vocab file: t2t_data/vocab.cnndailymail.32768
INFO:tensorflow:Not downloading, file already found: /tmp/t2t_datagen/all_train.txt
INFO:tensorflow:Found 287227 examples
INFO:tensorflow:Generating case 100000.
INFO:tensorflow:Generating case 200000.
INFO:tensorflow:Found vocab file: t2t_data/vocab.cnndailymail.32768
INFO:tensorflow:Downloading https://raw.githubusercontent.com/abisee/cnn-dailymail/master/url_lists/all_val.txt to /tmp/t2t_datagen/all_val.txt
100% completed
INFO:tensorflow:Succesfully downloaded all_val.txt, 2433674 bytes.
INFO:tensorflow:Found 13368 examples
INFO:tensorflow:Shuffling data...
WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Creating experiment, storing model files in exp_sum
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': 'exp_sum', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ffaa8376a90>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:batching_scheme = {'boundaries': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 33, 36, 39, 42, 46, 50, 55, 60, 66, 72, 79, 86, 94, 103, 113, 124, 136, 149, 163, 179, 196, 215, 236], 'window_size': 720, 'max_length': 256, 'batch_sizes': [240, 180, 180, 180, 144, 144, 144, 120, 120, 120, 90, 90, 90, 90, 80, 72, 72, 60, 60, 48, 48, 48, 40, 40, 36, 30, 30, 24, 24, 20, 20, 18, 18, 16, 15, 12, 12, 10, 10, 9, 8, 8], 'shuffle_queue_size': 270}
INFO:tensorflow:Reading data files from t2t_data/summarize_cnn_dailymail32k-train*
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 92, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 352, in run
    hparams=hparams)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 210, in run
    return _execute_schedule(experiment, schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 47, in _execute_schedule
    return task()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 660, in _call_train
    hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 558, in _train_model
    features, labels = input_fn()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 102, in input_fn
    name="problem_%d" % problem_idx)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 232, in features_for_problem
    dataset_split=dataset_split)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/data_reader.py", line 102, in input_pipeline
    dataset_split=dataset_split)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/problem.py", line 398, in dataset
    dataset = dataset.map(decode_record, num_threads=num_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 813, in map
    return MapDataset(self, map_func, num_threads, output_buffer_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1436, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 619, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/framework/function.py", line 167, in _create_definition_if_needed
    outputs = self._func(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1427, in tf_map_func
    flattened_ret = [ops.convert_to_tensor(t) for t in nest.flatten(ret)]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.
```

## Comments
It seems that it's not working with Python 3 for encoding reason. I may write a patch.

**Comment by frankdiehl** [comment]
Hi, today I've downloaded t2t and compiled the data without problems. When starting the training I though run into the same problem as reported above, i.e.:

....
File "/nrg5/hcnlp/data/users/frank_diehl/ACD/t2t_official_cnndailymail/venv_t2t_tf1.2.0_gpu/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.

Is this problem related to the underlying python version (I use Python 2.7.11)? Any support on this is highly appreciated.

Best
Frank

**Comment by vince62s** [comment]
@urvashik were you able to get decent results with this task ?

**Comment by frankdiehl** [comment]
I run a couple of experiments with the summarize_cnn_dailymail32k problem. 
Results are though rather bad (results below are on the val-set obtained during training with --eval_run_autoregressive set): 

PROBLEM=summarize_cnn_dailymail32k
MODEL=transformer

transformer_base_single_gpu     max_input_seq_length=100   max_target_seq_length=100      learning_rate=0.2         batch_size=2048
Step             rouge_2_fscore          rouge_L_fscore
645469           0.1638                      0.1499
740388           0.1554                      0.1467


transformer_base_single_gpu    max_input_seq_length=50   max_target_seq_length=50       learning_rate=0.2         batch_size=2048
Step             rouge_2_fscore          rouge_L_fscore
169911           0.1229                      0.1460
900000           0.1139                      0.1423


transformer_base_single_gpu   max_input_seq_length=100  max_target_seq_length=100    learning_rate=0.05        batch_size=1024
Step             rouge_2_fscore          rouge_L_fscore
1063285          0.1323                      0.1416
1292743          0.1308                      0.1294


transformer_big_single_gpu    max_input_seq_length=100   max_target_seq_length=100     learning_rate=0.05        batch_size=1024
Step             rouge_2_fscore          rouge_L_fscore
301559           0.1621                      0.1563
587090           0.1559                      0.1474

Though not directly comparable due to generated on the val-set and not on the test-set, all these numbers are far-far away 
from the lstm-2-lstm + attention numbers reported in Get To The Point: Summarization with Pointer-Generator Networks  https://arxiv.org/abs/1704.04368 
There the authors report ROUGE-1/2/L numbers:  31.33% / 11.81% / 28.83% on the test set.

So what is your experience on this.

**Comment by Santosh-Gupta** [comment]
I am wondering what's the easiest route to training other summarization datasets. Converting the Data to match the format of the CNN seems tricky. I think it may be better to somehow alter to code to accept a dataset whose format is simply two columns, one for the summary, one for the source.

**Pull request merged**
