### PR TITLE
Neural Shuffle-Exchange Seq2Seq model

### PR DESCRIPTION
**Pull request by OptimatiumFeles**
Added Neural Shuffle-Exchange model for Seq2Seq problems as described in [paper](https://papers.nips.cc/paper/8889-neural-shuffle-exchange-networks-sequence-processing-in-on-log-n-time) and [original code](https://github.com/LUMII-Syslab/shuffle-exchange).

### CODE REVIEW

**Comment by afrozenator** [comment]
Hi @OptimatiumFeles - Can you please fix the lint errors below before we take this in?

```
Lint errors found:
Invalid import order.
Diff:
    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function
    import six
    from tensor2tensor.layers import modalities
    from tensor2tensor.models import basic
    from tensor2tensor.models import bytenet
    from tensor2tensor.models import distillation
    from tensor2tensor.models import evolved_transformer
    from tensor2tensor.models import image_transformer
    from tensor2tensor.models import image_transformer_2d
    from tensor2tensor.models import lstm
    from tensor2tensor.models import mtf_image_transformer
    from tensor2tensor.models import mtf_resnet
    from tensor2tensor.models import mtf_transformer
    from tensor2tensor.models import mtf_transformer2
    from tensor2tensor.models import neural_assistant
    from tensor2tensor.models import neural_gpu
    from tensor2tensor.models import resnet
    from tensor2tensor.models import revnet
    from tensor2tensor.models import shake_shake
    from tensor2tensor.models import slicenet
    from tensor2tensor.models import text_cnn
    from tensor2tensor.models import transformer
    from tensor2tensor.models import vanilla_gan
    from tensor2tensor.models import xception
    from tensor2tensor.models.neural_architecture_search import nas_model
    from tensor2tensor.models.research import adafactor_experiments
    from tensor2tensor.models.research import aligned
    from tensor2tensor.models.research import attention_lm
    from tensor2tensor.models.research import attention_lm_moe
    from tensor2tensor.models.research import autoencoders
    from tensor2tensor.models.research import cycle_gan
    from tensor2tensor.models.research import gene_expression
    from tensor2tensor.models.research import glow
    from tensor2tensor.models.research import lm_experiments
    from tensor2tensor.models.research import moe_experiments
    from tensor2tensor.models.research import multiquery_paper
    from tensor2tensor.models.research import neural_stack
    from tensor2tensor.models.research import rl
+   from tensor2tensor.models.research import shuffle_network
    from tensor2tensor.models.research import similarity_transformer
    from tensor2tensor.models.research import super_lm
    from tensor2tensor.models.research import transformer_moe
    from tensor2tensor.models.research import transformer_nat
    from tensor2tensor.models.research import transformer_parallel
    from tensor2tensor.models.research import transformer_revnet
    from tensor2tensor.models.research import transformer_sketch
    from tensor2tensor.models.research import transformer_symshard
    from tensor2tensor.models.research import transformer_vae
    from tensor2tensor.models.research import universal_transformer
    from tensor2tensor.models.research import vqa_attention
    from tensor2tensor.models.research import vqa_recurrent_self_attention
    from tensor2tensor.models.research import vqa_self_attention
-   from tensor2tensor.models.research import shuffle_network
    from tensor2tensor.models.video import basic_deterministic
    from tensor2tensor.models.video import basic_recurrent
    from tensor2tensor.models.video import basic_stochastic
    from tensor2tensor.models.video import emily
    from tensor2tensor.models.video import epva
    from tensor2tensor.models.video import next_frame_glow
    from tensor2tensor.models.video import savp
    from tensor2tensor.models.video import sv2p
    from tensor2tensor.utils import registry
Copy and pastable ordering:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import six
from tensor2tensor.layers import modalities
from tensor2tensor.models import basic
from tensor2tensor.models import bytenet
from tensor2tensor.models import distillation
from tensor2tensor.models import evolved_transformer
from tensor2tensor.models import image_transformer
from tensor2tensor.models import image_transformer_2d
from tensor2tensor.models import lstm
from tensor2tensor.models import mtf_image_transformer
from tensor2tensor.models import mtf_resnet
from tensor2tensor.models import mtf_transformer
from tensor2tensor.models import mtf_transformer2
from tensor2tensor.models import neural_assistant
from tensor2tensor.models import neural_gpu
from tensor2tensor.models import resnet
from tensor2tensor.models import revnet
from tensor2tensor.models import shake_shake
from tensor2tensor.models import slicenet
from tensor2tensor.models import text_cnn
from tensor2tensor.models import transformer
from tensor2tensor.models import vanilla_gan
from tensor2tensor.models import xception
from tensor2tensor.models.neural_architecture_search import nas_model
from tensor2tensor.models.research import adafactor_experiments
from tensor2tensor.models.research import aligned
from tensor2tensor.models.research import attention_lm
from tensor2tensor.models.research import attention_lm_moe
from tensor2tensor.models.research import autoencoders
from tensor2tensor.models.research import cycle_gan
from tensor2tensor.models.research import gene_expression
from tensor2tensor.models.research import glow
from tensor2tensor.models.research import lm_experiments
from tensor2tensor.models.research import moe_experiments
from tensor2tensor.models.research import multiquery_paper
from tensor2tensor.models.research import neural_stack
from tensor2tensor.models.research import rl
from tensor2tensor.models.research import shuffle_network
from tensor2tensor.models.research import similarity_transformer
from tensor2tensor.models.research import super_lm
from tensor2tensor.models.research import transformer_moe
from tensor2tensor.models.research import transformer_nat
from tensor2tensor.models.research import transformer_parallel
from tensor2tensor.models.research import transformer_revnet
from tensor2tensor.models.research import transformer_sketch
from tensor2tensor.models.research import transformer_symshard
from tensor2tensor.models.research import transformer_vae
from tensor2tensor.models.research import universal_transformer
from tensor2tensor.models.research import vqa_attention
from tensor2tensor.models.research import vqa_recurrent_self_attention
from tensor2tensor.models.research import vqa_self_attention
from tensor2tensor.models.video import basic_deterministic
from tensor2tensor.models.video import basic_recurrent
from tensor2tensor.models.video import basic_stochastic
from tensor2tensor.models.video import emily
from tensor2tensor.models.video import epva
from tensor2tensor.models.video import next_frame_glow
from tensor2tensor.models.video import savp
from tensor2tensor.models.video import sv2p
from tensor2tensor.utils import registry
[g-bad-import-order]
	//depot/google3/third_party/py/tensor2tensor/models/__init__.py:61

Need 1 blank line before def [g-wrong-blank-lines]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:194

Line too long (100/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:57

Line too long (88/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:59

Line too long (83/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:61

Line too long (82/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:81

Line too long (102/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:82

Line too long (84/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:85

Line too long (91/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:92

Line too long (82/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:95

Line too long (107/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:99

Line too long (107/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:100

Line too long (112/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:116

Line too long (88/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:122

Line too long (92/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:123

Line too long (91/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:130

Line too long (82/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:137

Line too long (82/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:148

Line too long (90/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:155

Line too long (90/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:162

Wrong hanging indentation (add 2 spaces).
        forward_step,
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:168

Wrong hanging indentation (add 2 spaces).
        tf.range(0, n_bits),
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:169

Wrong hanging indentation (add 2 spaces).
        initializer=(block_out, residuals_queue),
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:170

Wrong hanging indentation (add 2 spaces).
        parallel_iterations=1,
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:171

Wrong hanging indentation (add 2 spaces).
        swap_memory=True
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:172

Line too long (95/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:175

Wrong hanging indentation (add 2 spaces).
        reverse_step,
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:179

Wrong hanging indentation (add 2 spaces).
        tf.range(n_bits, n_bits * 2),
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:180

Wrong hanging indentation (add 2 spaces).
        initializer=(forward_last, residuals_queue),
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:181

Wrong hanging indentation (add 2 spaces).
        parallel_iterations=1,
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:182

Wrong hanging indentation (add 2 spaces).
        swap_memory=True
        ^ |
[bad-continuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:183

Line too long (114/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:189

Line too long (95/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:209

Line too long (98/80) [line-too-long]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:210

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

Extraneous space in one-line docstring [g-short-docstring-space]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:19

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:19

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:29

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:39

Missing function docstring [missing-docstring]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:53-63

Missing class docstring [missing-docstring]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:66-138

Old-style class defined. [old-style-class]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:66-138

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:78

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:78

Args section is missing, does not match arg list or is badly indented.

Expected: inputs, suffix, bias_start, in_units, out_units

Found: 

Missing: inputs, suffix, bias_start, in_units, out_units

Unexpected: 
[g-doc-args]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:77

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:86

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:86

Args section is missing, does not match arg list or is badly indented.

Expected: inputs, suffix, bias_start_reset, in_units, out_units

Found: 

Missing: inputs, suffix, bias_start_reset, in_units, out_units

Unexpected: 
[g-doc-args]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:85

Use a != b rather than not a == b [g-comparison-negation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:129

Missing class docstring [missing-docstring]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:192-227

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:195

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:195

Args section is missing, does not match arg list or is badly indented.

Expected: features

Found: 

Missing: features

Unexpected: 
[g-doc-args]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:194

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:214

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:214

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:214

Args section is missing, does not match arg list or is badly indented.

Expected: logits, features

Found: 

Missing: logits, features

Unexpected: 
[g-doc-args]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:213

Missing function docstring [missing-docstring]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:231-252

Invalid import order.
Diff:
    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function
-   import tensorflow as tf
    from tensor2tensor.layers import common_hparams
    from tensor2tensor.utils import registry
    from tensor2tensor.utils import t2t_model
+   import tensorflow as tf
Copy and pastable ordering:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from tensor2tensor.layers import common_hparams
from tensor2tensor.utils import registry
from tensor2tensor.utils import t2t_model
import tensorflow as tf
[g-bad-import-order]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:13

```

**Comment by afrozenator** [comment]
Thanks for the PR though :-)

**Comment by OptimatiumFeles** [comment]
Hi @afrozenator, thank you for taking a look.
I've fixed all mentioned linting errors, hope that it'll be ok now.

**Comment by afrozenator** [comment]
A few more, we're almost there:

```
Lint errors found:
There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:1

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:21

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:42

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:62

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:62

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:62

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:84

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:98

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:130

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:130

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:136

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:136

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:136

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:152

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:172

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:172

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:207

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:207

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:249

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:266

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:266

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:334

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:334

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:362

One-line docstring summary should end with ".", ".)", "?", or "!" [g-short-docstring-punctuation]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:362

One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:362

There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:384

Missing Returns section in docstring, or wrong choice of Returns/Yields [g-doc-return-or-yield]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:398

Invalid import order.
Diff:
    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function
-   import tensorflow as tf
    from tensor2tensor.layers import common_hparams
    from tensor2tensor.utils import registry
    from tensor2tensor.utils import t2t_model
+   import tensorflow as tf
Copy and pastable ordering:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from tensor2tensor.layers import common_hparams
from tensor2tensor.utils import registry
from tensor2tensor.utils import t2t_model
import tensorflow as tf
[g-bad-import-order]
	//depot/google3/third_party/py/tensor2tensor/models/research/shuffle_network.py:15
```

**Comment by OptimatiumFeles** [comment]
Errors should be gone now.

**Comment by afrozenator** [comment]
Many many thanks for contributing and fixing the lints @OptimatiumFeles !

**Pull request merged**
