### PR TITLE
img2img_allen_brain problem defs

### PR DESCRIPTION
**Pull request by cwbeitel**
only outstanding issue blocking this should be that the test in allen_brain_test.py that uses tf.eager breaks many/all other t2t tests not compatible with eager mode.

squashed these:

commit 76c8cd3f105c07919f84d70b02b1fbd38b5376fe
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Fri Jun 15 18:35:13 2018 +0000

    fix mock_raw_data

commit f0dc3a0fcb6691c5b8854f419485966cb2f7b9c2
Merge: 3e17473 4b7360d
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Thu Jun 14 22:54:33 2018 +0000

    Merge branch 'allen-deps' of https://github.com/cwbeitel/tensor2tensor into allen-deps

commit 3e174736ec6628fe0b8097c1a3b0c2b3646ddee9
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Fri Jun 8 17:04:39 2018 +0000

    cleanup

commit 3e8ef9d61382afd795a26a16ffb254974a80dc8e
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Wed Jun 6 23:07:28 2018 +0000

    removed image summary writing from metrics

    training was 10x slower than CIFAR img2img problem, profiled and found 91% of time was being sp
ent writing ImageSummary's, removed that from metrics and saw the speed increase as expected.

commit 481455649596724da4ab7878eff7d84ed495af44
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Tue May 29 16:00:17 2018 +0000

    basic img2img prob. defs that maybe get data

commit 320f06c05697e35a108e74e7d3a0fbd29bebee3b
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Thu May 24 18:53:02 2018 +0000

    test without accessing network, follow rcfile

    * made test that accesses remote API optional, off by default
    * included test that runs sub-image extractor on mocked raw input image within mocked directory
 structure mirroring what would be produced by running actual data downloader
    * refactoring according to rcfile

commit 503123b09e1d784f9ca441c4b3f723d99baba7fb
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Wed May 23 22:09:31 2018 +0000

    add [allen] deps to travis setup

commit 239188b8c3e28d6fb0fb31c0d9167291874dc2f1
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Wed May 23 21:39:13 2018 +0000

    data download and sub-image gen utility

    * if additional [allen] deps not present suggest running `pip install tensor2tensor[allen]`
    * obtains a list of section dataset ID's from Allen Institute API
    * downloads specified number of raw images from specified number of section datasets
    * produces specified number of sub-images of specified size from raw images.
    * simple e2e test that runs the data downloader and sub-image generator with default parameters

commit af34cc660c90663b662eaa2bc7a5a66cfadf8762
Author: cwbeitel <me@cwbeitel-github.com>
Date:   Wed May 23 17:47:35 2018 +0000

    deps. for allen brain img probs. via extras

### CODE REVIEW

**Comment by cwbeitel** [comment]
@rsepassi Noticed many other tests were failing outside of allen_brain* tests with a bunch of errors about Eager mode, guessing the problem for those is my test that uses Eager.

**Comment by rsepassi** [comment]
Where are you seeing the errors about Eager mode? I don't see them in the Travis test logs.

When you run the tests locally with `pytest`, do they pass?

We'll want to ensure these all pass on Travis. One idea is that maybe it's problematic running the allen tests alongside all the others and we'll want to run them separately. You can see in the `.travis.yml` file examples of a test being ignored in the main run and then run separately afterwards.

**Comment by rsepassi** [comment]
Looks like the allen tests are failing.

**Comment by cwbeitel** [comment]
@rsepassi Those changes appear to have fixed everything except for a linter error in gym_utils, https://travis-ci.org/tensorflow/tensor2tensor/jobs/394214469#L2613,
```
pylint -j 2 tensor2tensor
Using config file /mnt/nfs-east1-d/work/prs/problem-def/pylintrc
************* Module tensor2tensor.data_generators.gym_utils
E1123: 31 WarmupWrapper.__init__: Unexpected keyword argument 'dtype' in constructor call [unexpected-keyword-arg]
W0221: 48 WarmupWrapper.reset: Parameters differ from overridden 'reset' method [arguments-differ]
E1123: 70 PongWrapper.__init__: Unexpected keyword argument 'dtype' in constructor call [unexpected-keyword-arg]
E1123:149 BreakoutWrapper.__init__: Unexpected keyword argument 'dtype' in constructor call [unexpected-keyword-arg]
```

Verified the allen_brain* files pass the linter locally.

**Comment by cwbeitel** [comment]
@rsepassi My bad, there was a little linter fix I made and forgot about. I can make those changes to gym_utils if that simplifies things.

**Comment by cwbeitel** [comment]
Hmm looks like those may not have actually been part of the problem on travis.

**Comment by cwbeitel** [comment]
@rsepassi Let me know if you're waiting on me for anything, otherwise no pressure!

**Comment by rsepassi** [comment]
Was just going through to merge it but noticed that AllenSDK has a non-permissive [license](https://github.com/AllenInstitute/AllenSDK/blob/master/LICENSE.txt) which actually makes it hard to import and use the code within Google. It may still be possible but it would be a lot of work and I just don't have the cycles to go through something like that right now unfortunately.

Now I don't want your work to go to waste so here's what I'm thinking: you can maintain a fork of `tensor2tensor` with the Allen problems so that people can generate the data and we'd be happy to have the Problems in `tensor2tensor` just without any AllenSDK dependency/import and the `generate_data` method could print out "To generate the data for XXX go to github/cwbeitel/tensor2tensor and run ....". Or something like that.

Very sorry about this, wish I noticed it earlier. What do you think?

**Comment by cwbeitel** [comment]
@rsepassi Hey! I removed the allensdk dependency but kept the data download utils which is far simpler if maintaining a list of image IDs (instead of building these through various queries to the API). There are 100 IDs included here randomly sampled across the full set of Mouse data. Given that we're considering 64 x 64px regions of images that are like 8.5k x 15k that's enough to generate around 3M examples. If that's not enough I referenced the API docs and a gist that includes the old download code.

**Comment by rsepassi** [comment]
Thank you @cwbeitel and sorry for the delay. Will merge shortly.

**Comment by cwbeitel** [comment]
@rsepassi No worries. Thank you.

**Pull request merged**
