### PR TITLE
Inference support for Neural Shuffle-Exchange network

### PR DESCRIPTION
**Pull request by OptimatiumFeles**
When target dimensions are not known, use hparams.max_length. max_length should be a power of 2.
Max length can be enforced using hparams.force_max_length=True.
Auto-Regressive decoding not supported at this moment.

### CODE REVIEW

**Comment by dfurrer** [comment]
I get the following linter error (and a crash when trying to run). Could you fix this in the request please?

`
third_party/py/tensor2tensor/models/research/shuffle_network.py:
364: Type annotations not enabled. (<string>, line 364) [syntax-error]
`

**Comment by OptimatiumFeles** [comment]
I hope this solves the problem.

**Comment by dfurrer** [comment]
Thanks. I have it running and the decode calls seem to work. However the linter now complains about these:
347: There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
347: One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
389: There should not be a space before a one-line docstring summary [g-space-before-docstring-summary]
389: One-line docstring summary should be followed by a blank line [g-no-space-after-docstring-summary]
389: Missing Returns section in docstring, or wrong choice of Returns/Yields [g-doc-return-or-yield]

**Comment by OptimatiumFeles** [comment]
Fixed those errors as well.

**Comment by afrozenator** [comment]
Many thanks to @OptimatiumFeles and @dfurrer both!

**Pull request merged**
