### PR TITLE
tensor2tensor: minor spelling tweaks

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by martinpopel** [comment]
yeah, mostly overlapping with my #690, but each PR has some extra tweaks:-)

**Comment by brettkoonce** [comment]
more than happy to rebase as needed!

**Comment by lukaszkaiser** [comment]
Merged Martin's earlier PR, please sync and only leave additional changes. Great thanks for doing this!

**Comment by brettkoonce** [comment]
@lukaszkaiser Let me know if you need anything else!

**Pull request merged**
