### PR TITLE
Fix dopamine import

### PR DESCRIPTION
**Pull request by lgeiger**
This *should* make Travis green again.

### CODE REVIEW

**Comment by lgeiger** [comment]
> This should make Travis green again.

Unfortunately it doesn't :(
But the fix should still be valid.

**Comment by afrozenator** [comment]
Thanks for pointing me out to this!

The correct fix is actually tricky -- since internally Dopamine is at 2.0 but they haven't pip released that version yet. I'm trying to come up with a fix that would work both internally and externally.

I'll close this once my fix works -- thanks again @lgeiger

**Comment by lgeiger** [comment]
> The correct fix is actually tricky -- since internally Dopamine is at 2.0 but they haven't pip released that version yet. I'm trying to come up with a fix that would work both internally and externally.

Thanks for the clarification :+1:

**Comment by afrozenator** [comment]
I pushed a change, https://github.com/tensorflow/tensor2tensor/commit/7b6ef710cf5cc79cefc2b012e2b396d7c3cd782e#diff-92a539a939ff4db57bdbe453e6482544 the discrete_domains change is hidden internally.

Closing this for now, but thanks again for pointing this out @lgeiger !

**Pull request closed without merging**
