### PR TITLE
inaccurate calculation of first_token's pos_embedding

### PR DESCRIPTION
**Pull request by real-brilliant**
since,
1. scaled_time is calculated by `scaled_time = tf.expand_dims(position, 1) * tf.expand_dims(inv_timescales, 0)`, while position_idx in position will **start by 0**.
2. scaled_time will be used to calculate position embedding by `signal = tf.concat([tf.sin(scaled_time), tf.cos(scaled_time)], axis=1)`

Thus, position_embedding of first token will always be combined with half zeros and half ones.

But the purpose of addding timing pos_embed should be helping model to learn relative and absolute position information between words by triangle relations of these words, i.e. sin(\alpha+\beta)=sin(\alpha)cos(\beta)+sin(\beta)cos(\alpha).

### CODE REVIEW

**Comment by real-brilliant** [comment]
@googlebot I signed it!

**Comment by real-brilliant** [comment]
@googlebot I signed it!

**Comment by real-brilliant** [comment]
@googlebot I fixed it.

**Comment by afrozenator** [comment]
Thanks @real-brilliant !

**Pull request merged**
