### PR TITLE
Remove a deadlock during saving debug video

### PR DESCRIPTION
**Pull request by koz4k**
The deadlock was due to the output pipe buffer from FFMPEG filling up, preventing the process from consuming next input frames.

### CODE REVIEW

**Comment by afrozenator** [comment]
Thanks @koz4k !

**Comment by afrozenator** [comment]
I presumed the merge went through and submitted internally as well, resulting in the internal version going before this one was merged by  GitHub -- Sorry about that.

To see a list of changes please see: https://github.com/tensorflow/tensor2tensor/commit/4c8216d568abf0e8bbc198b149a9840aee19fce9

**Comment by mbz** [comment]
Hi @koz4k @piotrmilos @lukaszkaiser

This PR seems to break the order of the frames i.e. the saved output video has shuffled frames (the video is extremely jumpy). if the generation speed is slower than decoding it might be fine, otherwise the order that the threads return the encoded frames seems to be random. We (@afrozenator  and I) confirmed this by reverting this change and seeing a very smooth video.

Let us revert the change and properly fix this. We also couldn't figure out the deadlock issue -- can you try to maintain the order of the threads? (The fifo commands don't seem to be doing that).

**Comment by koz4k** [comment]
Hi @mbz,

Thank you for reporting this. Do you have some code snippet that reproduces the bug?

**Comment by mbz** [comment]
Upon more investigation it turned out to be a False alarm. Sorry and thanks :)

**Comment by koz4k** [comment]
I'm glad to hear that, thank you :)

**Pull request merged**
