### PR TITLE
Add Transformer's encoder-decoder cache

### PR DESCRIPTION
**Pull request by jaywalnut310**
add Transformer's encoder-decoder cache
Additionally, add generation time checking code in decoding.py

### CODE REVIEW

**Comment by jaywalnut310** [comment]
I signed it!

**Comment by jaywalnut310** [comment]
For all test, the default Transformer config is used.
For simplicity, we assume source sentence length = target(inferenced) sentence length and all lengths of sentences in a dataset are equal.

** I use slightly modified one from this version of "decoding.py" for test, because it is needed to force matching source and target sentence length.
 
Fast: original Transformer with encoder-decoder & self attention caching
Default: original Transformer with self-attention caching
  

Batch Size Test

Batch size / Sentence length / Beam size | Elapsed Time (sec) (Fast/Default) | Averaged Single Token Generation Time (sec)(Fast/Default) | Ratio (Fast/Default)(Lower is better)
-- | -- | -- | --
32 / 20 / 1 | 21.14063 / 22.09728 | 0.0032901 / 0.0034372 | 0.9572
64 / 20 / 1 | 21.28419 / 21.65552 | 0.0016497 / 0.0016777 | 0.9833
128 / 20 / 1 | 21.98650 / 22.84949 | 0.0008455 / 0.0008792 | 0.9617
256 / 20 / 1 | 23.93520 / 24.65760 | 0.0004525 / 0.0004687 | 0.9654
512 / 20 / 1 | 26.93354 / 28.78737 | 0.0002495 / 0.0002670 | 0.9344
1024 / 20 / 1 | 35.93564 / 40.00386 | 0.0001626 / 0.0001823 | 0.8919

Sentence Length Test

Batch size / Sentence length / Beam size | Elapsed Time (sec) (Fast/Default) | Averaged Single Token Generation Time (sec)(Fast/Default) | Ratio (Fast/Default)(Lower is better)
-- | -- | -- | --
128 / 30 / 1 | 24.03509 / 25.49503 | 0.0006123 / 0.0006508 | 0.9408
128 / 40 / 1 | 26.40903 / 28.63231 | 0.0005036 / 0.0005462 | 0.9220
128 / 50 / 1 | 29.18022 / 32.69734 | 0.0004430 / 0.0004982 | 0.8892
128 / 60 / 1 | 31.33252 / 36.11756 | 0.0003953 / 0.0004575 | 0.8640
128 / 100 / 1 | 42.40771 / 56.15577 | 0.0003195 / 0.0004258 | 0.7504
128 / 200 / 1 | 76.11935 / 129.75659 | 0.0002857 / 0.0004954 | 0.5767

Beam Size Test

Batch size / Sentence length / Beam size | Elapsed Time (sec) (Fast/Default) | Averaged Single Token Generation Time (sec)(Fast/Default) | Ratio (Fast/Default)(Lower is better)
-- | -- | -- | --
128 / 50 / 2 | 40.71480 / 41.98204 | 0.0006170 / 0.0006390 | 0.9658
128 / 50 / 4 | 53.71522 / 57.31317 | 0.0008207 / 0.0008771 | 0.9357
128 / 50 / 8 | 78.39686 / 87.28801 | 0.0012077 / 0.0013464 | 0.8970
128 / 50 / 12 | 104.87851 / 117.95966 | 0.0016206 / 0.0018248 | 0.8881
128 / 50 / 16 | 131.46122 / 149.23508 | 0.0020360 / 0.0023135 | 0.8801
128 / 50 / 32 | 237.44361 / 274.65529 | 0.0036908 / 0.0042738 | 0.8636

**Comment by yuananzhang** [comment]
the code is not clean. it's not that faster as i thought, and it would need more memory. why not try mutlti-gpu decode?

**Comment by afrozenator** [comment]
Thanks @jaywalnut310 -- this is awesome!

**Comment by afrozenator** [comment]
For googlebot : A comment earlier in the thread indicates the CLA has been signed.

**Pull request merged**
