### PR TITLE
RNN baselines (requires TF 1.4)

### PR DESCRIPTION
**Pull request by fstahlberg**
This PR adds the [TF NMT tutorial](https://github.com/tensorflow/nmt) to the subdirectory tensor2tensor/models/tfnmt and integrates it into the T2T infrastructure.

Note that some of the models (for example the GNMT encoder) require TensorFlow 1.4.

### CODE REVIEW

**Comment by fstahlberg** [comment]
This PR contains the entire code base of the tutorial - We don't need the entire code base, but I tried to keep the modifications to it at a minimum to make sure that we can still pull upstream commits without causing too many conflicts.

**Comment by lukaszkaiser** [comment]
Sorry, but I think that importing the whole repo (with docs and LICENCE and everything) is too much! Please, could you just import the models? I think that's all we need!

**Comment by fstahlberg** [comment]
Okay, I've removed all unnecessary files. I could shrink it even more by deleting the unused bits in the existing files, but this would ultimately reduce the chance to sync with the upstream repository. If having a slim code base is more important I'm happy to do that.

**Comment by zh794390558** [comment]
@fstahlberg This PR does not using T2T frame.

**Comment by fstahlberg** [comment]
Not sure if I understand. It adds a stripped down version of the TF-NMT tutorial to  tensor2tensor/models/tfnmt/. In there I tried to be as close to the original tutorial as possible to make it possible to update it once the tutorial is updated. The adaptor code to T2T is in tensor2tensor/models/tfnmt_model.py

**Comment by zh794390558** [comment]
@fstahlberg I mean these model does not include a Problem, Modality.  The t2t input pipeline does not have input length info, which maybe not able to used in BiLSTM model.

**Comment by fstahlberg** [comment]
It works eg. with the translate_ende_wmt32k problem. You are right that t2t does not expose the sequence lengths, but this may be better addressed in a separate PR (it applies to the current lstm model too). For now, similarly to the current lstm model, the sequence lengths are derived from the position of PAD symbols in the raw features.

**Comment by zh794390558** [comment]
@fstahlberg https://github.com/tensorflow/tensorflow/issues/5588  input length be optional now.

**Comment by rsepassi** [comment]
Could you add a test to verify that this all works? Specifically one that exercises `TFNmt`, the subclass of `T2TModel`.

**Comment by fstahlberg** [comment]
This PR needs to be updated for the recent changes in the T2T architecture. I'll close it for now, and reopen it (with tests) once I have time again to work on it.

**Pull request closed without merging**
