### PR TITLE
Set precision and recall metrics

### PR DESCRIPTION
**Pull request by epurdyf**

### CODE REVIEW

**Comment by epurdyf** [comment]
I signed the CLA.

**Comment by epurdyf** [comment]
I signed the CLA.

**Comment by epurdyf** [comment]
I signed the CLA.

**Comment by epurdyf** [comment]
I signed the CLA.

**Comment by epurdyf** [comment]
I signed the CLA. fdkfjdkjfkdljfd

**Comment by epurdyf** [comment]
I signed the CLA.

**Comment by lukaszkaiser** [comment]
Sorry for the CLA problems, all looks fine now. Great thanks for the PR!

**Pull request merged**
