### PR TITLE
Fix for string features

### PR DESCRIPTION
**Pull request by epurdy**

### CODE REVIEW

**Comment by lukaszkaiser** [comment]
Great thanks! This is very needed and we'd love to check in, but despite it being one like we need you to accept the CLA, can you do that? Or at least add a comment that you're ok with it?

**Comment by epurdy** [comment]
I signed it!

**Comment by afrozenator** [comment]
@googlebot

**Comment by epurdy** [comment]
@googlebot I signed it!

**Comment by epurdy** [comment]
@googlebot I signed it!

**Comment by epurdy** [comment]
I signed it!

**Comment by afrozenator** [comment]
Thanks @epurdy !

**Pull request merged**
