### PR TITLE
add a metrics for calculating pearson correlation coefficient

### PR DESCRIPTION
**Pull request by luffy06**
Dear community, I'm using tensor2tensor for text similarity tasks and I find no metrics for calculating pearson correlation coefficient.

### CODE REVIEW

**Comment by afrozenator** [comment]
Hi @luffy06 - Thanks for the PR - I was qualifying the change internally to accept in the main branch, any reason you closed this PR?

Thanks!

**Comment by luffy06** [comment]
I'm sorry, there are some bugs when it is building on Travis-CI. I'll fix it and make a pull request again.

**Comment by afrozenator** [comment]
I just found out that the test is slightly broken 

```
ValueError: Can not squeeze dim[2], expected a dimension of 1, got 4 for 'pearson_r/remove_squeezable_dimensions/Squeeze' (op: 'Squeeze') with input shapes: [12,1,4].
```

Please note that travis is currently broken, so if your metrics_test passes locally, you should be fine -- thanks again for this, this is very nice addtion.

**Comment by afrozenator** [comment]
Just reopen this when you are done and then we can take it forward. Thanks again!

**Comment by luffy06** [comment]
There are some errors in my metric_test method, I'm fixing it.

**Comment by luffy06** [comment]
Hi @afrozenator, I've fixed my code errors and built success in [Travis](https://travis-ci.org/xy-always/tensor2tensor/builds/463688803). Please qualify my PR. Thanks a lot.

**Comment by afrozenator** [comment]
Beautiful! Many thanks @luffy06 !

**Pull request merged**
