### PR TITLE
Add Fast Decoding  Support For Relative Dot Product

### PR DESCRIPTION
**Pull request by aeloyq**
Add Fast Decoding  Support For And Only For Relative Dot Product by enabling caching mechanism.
This pr have been tested on "En-Zh" case and got the same results as expected.

### CODE REVIEW

**Comment by aeloyq** [comment]
Check CLA again.

**Comment by afrozenator** [comment]
thanks a lot @aeloyq !

**Comment by aeloyq** [comment]
There's a typo in 

> tensor2tensor/models/transformer.py line-276


`if self._hparams.self_attention_type not in ["dot_product", "dot_product_relative1"]:`

should be modified to:

`if self._hparams.self_attention_type not in ["dot_product", "dot_product_relative"]:`

**Comment by afrozenator** [comment]
Thanks - yes @lukaszkaiser pointed that out, we fixed it on our end.

**Pull request merged**
