### PR TITLE
use `chr` in Python 3

### PR DESCRIPTION
**Pull request by ninotoshi**
This PR resolves the error `NameError: name 'unichr' is not defined` in Python 3.

### CODE REVIEW

**Comment by ninotoshi** [comment]
signed the CLA

**Comment by deasuke** [comment]
`from six import unichr` looks better.

**Comment by ninotoshi** [comment]
Thank you, @deasuke. It's updated.

**Comment by martinpopel** [comment]
#123 fixes also `tokenizer_test.py`

**Comment by ninotoshi** [comment]
I'll close this.

**Pull request closed without merging**
