### PR TITLE
Simplify is_unicode()

### PR DESCRIPTION
**Pull request by cclauss**
https://six.readthedocs.io/#six.text_type

### CODE REVIEW

**Comment by afrozenator** [comment]
thanks a lot @cclauss -- much appreciated!

**Comment by cclauss** [comment]
@afrozenator Unfortunately, the merge of #1321 overwrote the change in this PR #1318.  This change should still be made.

**Comment by afrozenator** [comment]
@cclauss - I see both the functions correctly at master - https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder.py

**Comment by cclauss** [comment]
You are correct.  I was mistaken.  Thanks.

**Comment by afrozenator** [comment]
I've been tripped up in the past by this, it is very confusing.

**Pull request merged**
