### PR TITLE
Add Yelp_Review Dataset

### PR DESCRIPTION
**Pull request by ksboy**
I added yelp_review dataset including Yelp_review_full and yelp_review_polarity,  which is proposed by Xiang Zhang in [Paper](https://arxiv.org/abs/1509.01626) **Character-level Convolutional Networks for Text Classification** .

### CODE REVIEW

**Comment by ksboy** [comment]
> I signed it!

**Comment by ksboy** [comment]
image
My Request did not pass the check of travis-ci. 
I have checked job log and wondered if it is possible that there is something wrong with travis-ci.

**Comment by afrozenator** [comment]
> image
> My Request did not pass the check of travis-ci.
> I have checked job log and wondered if it is possible that there is something wrong with travis-ci.

Travis is broken by other tests failing, adding a new dataset should be fine, I'll doubllt check internally.

PS: Can you also add this to https://github.com/tensorflow/datasets ?

**Comment by afrozenator** [comment]
Thanks a lot for this @ksboy -- we'll fix a few nits on our end, thanks a lot for contributing!

**Comment by ksboy** [comment]
> > image
> > My Request did not pass the check of travis-ci.
> > I have checked job log and wondered if it is possible that there is something wrong with travis-ci.
> 
> Travis is broken by other tests failing, adding a new dataset should be fine, I'll doubllt check internally.
> 
> PS: Can you also add this to https://github.com/tensorflow/datasets ?

I will when I am free

**Comment by afrozenator** [comment]
Many thanks for adding it in the first place!

**Pull request merged**
